# -*- coding: utf-8
#from __future__ import unicode_literals
bar = {
"Single": "|",
"Double": "\\bar\"||\"",
"BrokenSingle": "\\bar\"!\"",
"BrokenDouble": "\\bar\"!!\"",
"SectionOpen": "\\bar\".|\"",
"SectionClose": "\\bar\"|.\"",
"SectionCloseOpen": "\\bar\"|.|\"",
"LocalRepeatOpen": "\\bar\"||:\"",
"LocalRepeatClose": "\\bar\":||\"",
"LocalRepeatCloseOpen": "\\bar\":|||:\"",
"MasterRepeatOpen": "\\bar\".|:\"",
"MasterRepeatClose": "\\bar\":|.\"",
"MasterRepeatCloseOpen": "\\bar\":|.|:\"",
"Transparent": "\\bar\"\"",
}

endbar = {
"Section Close": "|.",
"Master Repeat Close": ":|.",
"Single": "|",
"Double": "||",
"Open (hidden)": ""}

tempo = {
"Eighth":"8",
"Eighth Dotted":"8.",
"Quarter":"4",
"Quarter Dotted":"4.",
"Half":"2",
"Half Dotted":"2."}

tempovar = {
"Accelerando": "accel.",
"Allargando": "allarg.",
"Rallentando": "rall.",
"Ritardando": "ritard.",
"Ritenuto": "rit.",
"Rubato": "rubato",
"Stringendo": "string."}

textcmd = {
"\uF026": "\\turn",
"\uF02B": "\\stopped",
"\uF02D": "\\prall",
"\uF03C": "\\downbow",
"\uF03E": "\\upbow",
"\uF060": "\\trill",
"tr": "\\trill",
}

textsmall = {
"\uF026": "\\markup\\tiny\\musicglyph #\"scripts.turn\"",
"\uF027": "\\markup\\tiny\\musicglyph #\"scripts.caesura.straight\"",
"\uF028": "\\markup\\tiny\\musicglyph #\"accidentals.leftparen\"" ,
"\uF029": "\\markup\\tiny\\musicglyph #\"accidentals.rightparen\"" ,
"\uF02B": "\\markup\\tiny\\musicglyph #\"plus\"",
"\uF02D": "\\markup\\tiny\\musicglyph #\"scripts.trill_element\"",
"\uF030": "\\markup\\tiny\\musicglyph #\"zero\"",
"\uF031": "\\markup\\tiny\\musicglyph #\"one\"",
"\uF032": "\\markup\\tiny\\musicglyph #\"two\"",
"\uF033": "\\markup\\tiny\\musicglyph #\"three\"",
"\uF034": "\\markup\\tiny\\musicglyph #\"four\"",
"\uF035": "\\markup\\tiny\\musicglyph #\"five\"",
"\uF036": "\\markup\\tiny\\musicglyph #\"six\"",
"\uF037": "\\markup\\tiny\\musicglyph #\"seven\"",
"\uF038": "\\markup\\tiny\\musicglyph #\"eight\"",
"\uF039": "\\markup\\tiny\\musicglyph #\"nine\"",
"\uF03A": "\\markup\\tiny\\musicglyph #\"scripts.dstaccatissimo\"",
"\uF03B": "\\markup\\tiny\\musicglyph #\"scripts.ustaccatissimo\"",
"\uF03C": "\\markup\\tiny\\musicglyph #\"scripts.downbow\"",
"\uF03D": "\\markup\\tiny\\score{s\\layout{\\context{\\Staff\\remove\"Time_signature_engraver\"\\remove\"Clef_engraver\"}indent=0}}",
"\uF03E": "\\markup\\tiny\\musicglyph #\"scripts.upbow\"",
"\uF040": "\\markup\\tiny\\musicglyph #\"scripts.dmarcato\"",
"\uF041": "\\markup\\tiny\\musicglyph #\"scripts.sforzato\"",
"\uF042": "\\markup\\tiny\\musicglyph #\"scripts.umarcato\"",
"\uF043": "\\markup\\tiny\\musicglyph #\"scripts.tenuto\"",
"\uF044": "\\markup\\tiny\\musicglyph #\"timesig.C44\"",
"\uF045": "\\markup\\tiny\\musicglyph #\"timesig.C22\"",
"\uF046": "\\markup\\tiny\\note #\"2\" #UP",
"\uF047": "\\markup\\tiny\\note #\"4\" #UP",
"\uF048": "\\markup\\tiny\\note #\"8\" #UP",
"\uF049": "\\markup\\tiny\\musicglyph #\"comma\"",
"\uF04A": "\\markup\\tiny\":\"",
"\uF04B": "\\markup\\tiny\\musicglyph #\"accordion.oldEE\"",
"\uF050": "\\markup\\tiny\\dynamic\"ppp\"",
"\uF051": "\\markup\\tiny\\dynamic\"pp\"",
"\uF052": "\\markup\\tiny\\dynamic\"p\"",
"\uF053": "\\markup\\tiny\\dynamic\"mp\"",
"\uF054": "\\markup\\tiny\\dynamic\"mf\"",
"\uF055": "\\markup\\tiny\\dynamic\"f\"",
"\uF056": "\\markup\\tiny\\dynamic\"ff\"",
"\uF057": "\\markup\\tiny\\dynamic\"fff\"",
"\uF058": "\\markup\\tiny\\musicglyph #\"noteheads.s2cross\"",
"\uF059": "\\markup\\tiny\\musicglyph #\"noteheads.s0harmonic\"",
"\uF05A": "\\markup\\tiny\\musicglyph #\"noteheads.s2harmonic\"",
"\uF05B": "\\markup\\tiny\\musicglyph #\"noteheads.sM1double\"",
"\uF060": "\\markup\\tiny\\musicglyph #\"scripts.trill\"",
"\uF061": "\\markup\\musicglyph #\"clefs.G_change\"",
"\uF062": "\\markup\\musicglyph #\"clefs.F_change\"",
"\uF063": "\\markup\\musicglyph #\"clefs.C_change\"",
"\uF064": "\\markup\\tiny\\musicglyph #\"accidentals.sharp\"",
"\uF065": "\\markup\\tiny\\musicglyph #\"accidentals.natural\"",
"\uF066": "\\markup\\tiny\\musicglyph #\"accidentals.flat\"",
"\uF067": "\\markup\\tiny\\musicglyph #\"accidentals.doublesharp\"",
"\uF068": "\\markup\\tiny\\musicglyph #\"accidentals.flatflat\"",
"\uF069": "\\markup\\tiny\\musicglyph #\"noteheads.s0\"",
"\uF06A": "\\markup\\tiny\\musicglyph #\"noteheads.s1\"",
"\uF06B": "\\markup\\tiny\\musicglyph #\"noteheads.s2\"",
"\uF06C": "\\markup\\tiny\\musicglyph #\"rests.0o\"",
"\uF06D": "\\markup\\tiny\\musicglyph #\"rests.1o\"",
"\uF06E": "\\markup\\tiny\\musicglyph #\"rests.2\"",
"\uF06F": "\\markup\\tiny\\musicglyph #\"rests.3\"",
"\uF070": "\\markup\\tiny\\musicglyph #\"rests.4\"",
"\uF071": "\\markup\\tiny\\musicglyph #\"rests.5\"",
"\uF072": "\\markup\\tiny\\musicglyph #\"rests.6\"",
"\uF073": "\\markup\\tiny\\italic\"3\"",
"\uF074": "\\markup\\tiny\\musicglyph #\"scripts.dfermata\"",
"\uF075": "\\markup\\tiny\\musicglyph #\"pedal.Ped\"",
"\uF076": "\\markup\\tiny\\musicglyph #\"pedal.*\"",
"\uF077": "\\markup\\tiny\\musicglyph #\"scripts.coda\"",
"\uF078": "\\markup\\tiny\\musicglyph #\"scripts.segno\"",
"\uF079": "\\markup\\tiny\\musicglyph #\"scripts.ufermata\"",
"\uF07A": "\\markup\\tiny\\musicglyph #\"dots.dot\"",
"\uF07B": "\\markup\\tiny\\musicglyph #\"rests.M1\"",
"\uF07C": "\\markup\\tiny\"|\"",
"\uF07E": "\\markup\\tiny\"~\"",
"\uF082": "\\markup\\tiny\\musicglyph #\"flags.u3\"",
"\uF083": "\\markup\\tiny\\musicglyph #\"flags.u4\"",
"\uF084": "\\markup\\tiny\\musicglyph #\"flags.u5\"",
"\uF085": "\\markup\\tiny\\musicglyph #\"flags.u6\"",
"\uF087": "\\markup\\tiny\\musicglyph #\"flags.d3\"",
"\uF088": "\\markup\\tiny\\musicglyph #\"flags.d4\"",
"\uF089": "\\markup\\tiny\\musicglyph #\"flags.d5\"",
"\uF08A": "\\markup\\tiny\\musicglyph #\"flags.d6\"",
"\uF090": "\\markup\\tiny\\musicglyph #\"noteheads.u1do\"",
"\uF091": "\\markup\\tiny\\musicglyph #\"noteheads.u2do\"",
"\uF092": "\\markup\\tiny\\musicglyph #\"noteheads.u1re\"",
"\uF093": "\\markup\\tiny\\musicglyph #\"noteheads.u2re\"",
"\uF094": "\\markup\\tiny\\musicglyph #\"noteheads.s1mi\"",
"\uF095": "\\markup\\tiny\\musicglyph #\"noteheads.s2mi\"",
"\uF096": "\\markup\\tiny\\musicglyph #\"noteheads.u1fa\"",
"\uF097": "\\markup\\tiny\\musicglyph #\"noteheads.u2fa\"",
"\uF098": "\\markup\\tiny\\musicglyph #\"noteheads.d1fa\"",
"\uF099": "\\markup\\tiny\\musicglyph #\"noteheads.d2fa\"",
"\uF09A": "\\markup\\tiny\\musicglyph #\"noteheads.s1sol\"",
"\uF09B": "\\markup\\tiny\\musicglyph #\"noteheads.s2sol\"",
"\uF09C": "\\markup\\tiny\\musicglyph #\"noteheads.s1la\"",
"\uF09D": "\\markup\\tiny\\musicglyph #\"noteheads.s2la\"",
"\uF09E": "\\markup\\tiny\\musicglyph #\"noteheads.u1ti\"",
"\uF09F": "\\markup\\tiny\\musicglyph #\"noteheads.u2ti\"",
}

textlarge = {
"\uF026": "\\markup\\musicglyph #\"scripts.turn\"",
"\uF027": "\\markup\\musicglyph #\"scripts.caesura.straight\"",
"\uF028": "\\markup\\musicglyph #\"accidentals.leftparen\"",
"\uF029": "\\markup\\musicglyph #\"accidentals.rightparen\"",
"\uF02B": "\\markup\\musicglyph #\"plus\"",
"\uF02D": "\\markup\\musicglyph #\"scripts.trill_element\"",
"\uF030": "\\markup\\musicglyph #\"zero\"",
"\uF031": "\\markup\\musicglyph #\"one\"",
"\uF032": "\\markup\\musicglyph #\"two\"",
"\uF033": "\\markup\\musicglyph #\"three\"",
"\uF034": "\\markup\\musicglyph #\"four\"",
"\uF035": "\\markup\\musicglyph #\"five\"",
"\uF036": "\\markup\\musicglyph #\"six\"",
"\uF037": "\\markup\\musicglyph #\"seven\"",
"\uF038": "\\markup\\musicglyph #\"eight\"",
"\uF039": "\\markup\\musicglyph #\"nine\"",
"\uF03A": "\\markup\\musicglyph #\"scripts.dstaccatissimo\"",
"\uF03B": "\\markup\\musicglyph #\"scripts.ustaccatissimo\"",
"\uF03C": "\\markup\\musicglyph #\"scripts.downbow\"",
"\uF03D": "\\markup\\score{s\\layout{\\context{\\Staff\\remove\"Time_signature_engraver\"\\remove\"Clef_engraver\"}indent=0}}",
"\uF03E": "\\markup\\musicglyph #\"scripts.upbow\"",
"\uF040": "\\markup\\musicglyph #\"scripts.dmarcato\"",
"\uF041": "\\markup\\musicglyph #\"scripts.sforzato\"",
"\uF042": "\\markup\\musicglyph #\"scripts.umarcato\"",
"\uF043": "\\markup\\musicglyph #\"scripts.tenuto\"",
"\uF044": "\\markup\\musicglyph #\"timesig.C44\"",
"\uF045": "\\markup\\musicglyph #\"timesig.C22\"",
"\uF046": "\\markup\\note #\"2\" #UP",
"\uF047": "\\markup\\note #\"4\" #UP",
"\uF048": "\\markup\\note #\"8\" #UP",
"\uF049": "\\markup\\musicglyph #\"comma\"",
"\uF04A": "\\markup\":\"",
"\uF04B": "\\markup\\musicglyph #\"accordion.oldEE\"",
"\uF050": "\\markup\\dynamic\"ppp\"",
"\uF051": "\\markup\\dynamic\"pp\"",
"\uF052": "\\markup\\dynamic\"p\"",
"\uF053": "\\markup\\dynamic\"mp\"",
"\uF054": "\\markup\\dynamic\"mf\"",
"\uF055": "\\markup\\dynamic\"f\"",
"\uF056": "\\markup\\dynamic\"ff\"",
"\uF057": "\\markup\\dynamic\"fff\"",
"\uF058": "\\markup\\musicglyph #\"noteheads.s2cross\"",
"\uF059": "\\markup\\musicglyph #\"noteheads.s0harmonic\"",
"\uF05A": "\\markup\\musicglyph #\"noteheads.s2harmonic\"",
"\uF05B": "\\markup\\musicglyph #\"noteheads.sM1double\"",
"\uF060": "\\markup\\musicglyph #\"scripts.trill\"",
"\uF061": "\\markup\\musicglyph #\"clefs.G\"",
"\uF062": "\\markup\\musicglyph #\"clefs.F\"",
"\uF063": "\\markup\\musicglyph #\"clefs.C\"",
"\uF064": "\\markup\\musicglyph #\"accidentals.sharp\"",
"\uF065": "\\markup\\musicglyph #\"accidentals.natural\"",
"\uF066": "\\markup\\musicglyph #\"accidentals.flat\"",
"\uF067": "\\markup\\musicglyph #\"accidentals.doublesharp\"",
"\uF068": "\\markup\\musicglyph #\"accidentals.flatflat\"",
"\uF069": "\\markup\\musicglyph #\"noteheads.s0\"",
"\uF06A": "\\markup\\musicglyph #\"noteheads.s1\"",
"\uF06B": "\\markup\\musicglyph #\"noteheads.s2\"",
"\uF06C": "\\markup\\musicglyph #\"rests.0o\"",
"\uF06D": "\\markup\\musicglyph #\"rests.1o\"",
"\uF06E": "\\markup\\musicglyph #\"rests.2\"",
"\uF06F": "\\markup\\musicglyph #\"rests.3\"",
"\uF070": "\\markup\\musicglyph #\"rests.4\"",
"\uF071": "\\markup\\musicglyph #\"rests.5\"",
"\uF072": "\\markup\\musicglyph #\"rests.6\"",
"\uF073": "\\markup\\italic\"3\"",
"\uF074": "\\markup\\musicglyph #\"scripts.dfermata\"",
"\uF075": "\\markup\\musicglyph #\"pedal.Ped\"",
"\uF076": "\\markup\\musicglyph #\"pedal.*\"",
"\uF077": "\\markup\\musicglyph #\"scripts.coda\"",
"\uF078": "\\markup\\musicglyph #\"scripts.segno\"",
"\uF079": "\\markup\\musicglyph #\"scripts.ufermata\"",
"\uF07A": "\\markup\\musicglyph #\"dots.dot\"",
"\uF07B": "\\markup\\musicglyph #\"rests.M1\"",
"\uF07C": "\\markup\"|\"",
"\uF07E": "\\markup\"~\"",
"\uF082": "\\markup\\musicglyph #\"flags.u3\"",
"\uF083": "\\markup\\musicglyph #\"flags.u4\"",
"\uF084": "\\markup\\musicglyph #\"flags.u5\"",
"\uF085": "\\markup\\musicglyph #\"flags.u6\"",
"\uF087": "\\markup\\musicglyph #\"flags.d3\"",
"\uF088": "\\markup\\musicglyph #\"flags.d4\"",
"\uF089": "\\markup\\musicglyph #\"flags.d5\"",
"\uF08A": "\\markup\\musicglyph #\"flags.d6\"",
"\uF090": "\\markup\\musicglyph #\"noteheads.u1do\"",
"\uF091": "\\markup\\musicglyph #\"noteheads.u2do\"",
"\uF092": "\\markup\\musicglyph #\"noteheads.u1re\"",
"\uF093": "\\markup\\musicglyph #\"noteheads.u2re\"",
"\uF094": "\\markup\\musicglyph #\"noteheads.s1mi\"",
"\uF095": "\\markup\\musicglyph #\"noteheads.s2mi\"",
"\uF096": "\\markup\\musicglyph #\"noteheads.u1fa\"",
"\uF097": "\\markup\\musicglyph #\"noteheads.u2fa\"",
"\uF098": "\\markup\\musicglyph #\"noteheads.d1fa\"",
"\uF099": "\\markup\\musicglyph #\"noteheads.d2fa\"",
"\uF09A": "\\markup\\musicglyph #\"noteheads.s1sol\"",
"\uF09B": "\\markup\\musicglyph #\"noteheads.s2sol\"",
"\uF09C": "\\markup\\musicglyph #\"noteheads.s1la\"",
"\uF09D": "\\markup\\musicglyph #\"noteheads.s2la\"",
"\uF09E": "\\markup\\musicglyph #\"noteheads.u1ti\"",
"\uF09F": "\\markup\\musicglyph #\"noteheads.u2ti\"",
}

dynamic = {
"Crescendo": "cresc",
"Decrescendo": "decresc",
"Diminuendo": "dim",
"Rinforzando": "rfz",
"Sforzando": "sfz",
}

performstyle = {
"Ad Libitum": "ad lib.",
"Animato": "animato",
"Cantabile": "cantabile",
"Con brio": "con brio",
"Dolce": "dolce",
"Espressivo": "espress.",
"Grazioso": "grazioso",
"Legato": "legato",
"Maestoso": "maestoso",
"Marcato": "marc.",
"Meno mosso": "meno mosso",
"Poco a poco": "poco a poco",
"Pi\\xf9 mosso": "più mosso",
"Semplice": "semplice",
"Simile": "simile",
"Solo": "solo",
"Sostenuto": "sostenuto",
"Sotto Voce": "sotto voce",
"Staccato": "staccato",
"Subito": "subito",
"Tenuto": "tenuto",
"Tutti": "tutti",
"Volta Subito": "volta subito"}

flow = {
"Coda": "\\musicglyph #\"scripts.coda\" ",
"Segno": "\\musicglyph #\"scripts.segno\" ",
"Fine": "\"fine\"",
"ToCoda": "\\musicglyph #\"scripts.coda\" ",
"DaCapo": "\"D.C.\"",
"DCalCoda": "{\"D.C. al \"\\raise #1.0 \\musicglyph #\"scripts.coda\"}",
"DCalFine": "\"D.C. al fine\"",
"DalSegno": "\"D.S.\"",
"DSalCoda": "{\"D.S. al\"\\raise #1.0 \\musicglyph #\"scripts.coda\"}",
"DSalFine": "\"D.S. al fine\""}
